---
detectors:
  IrresponsibleModule:
    enabled: false
  UncommunicativeVariableName:
    accept:
      - b
      - c
      - e
      - m
      - p
      - r
      - w
  NestedIterators:
    max_allowed_nesting: 2
  TooManyStatements:
    max_statements: 12
  MissingSafeMethod:
    enabled: false
  InstanceVariableAssumption:
    enabled: false
  TooManyInstanceVariables:
    max_instance_variables: 6

exclude_paths:
  - test/
  - config/
  - db/
