#!/usr/bin/env bash

source "/home/odziozo/.rvm/gems/ruby-3.2.0@global/environment"

cd /home/odziozo/rails7/lcyc/current
# for test only
#cd /home/odziozo/rails5/lcyc/staging
bundle exec rake RAILS_ENV=production chores:daily
