# app/controllers/mission_control_controller.rb
class MissionControlController < ApplicationController
  # This uses the 'require_authentication' method generated by Rails 8
  before_action :check_authorization

  private

  def ensure_admin
    # Replace '.admin?' with whatever logic you use to identify admins
    unless Current.user.admin?
      redirect_to root_path, alert: "Access denied."
    end
  end
end
